[daily]
# Inclusive rarity range (min ≤ rarity ≤ max)
# Both values are inclusive.

min_rarity_daily = 45.0
max_rarity_daily = 197.0

[weekly]
# Inclusive rarity range (min ≤ rarity ≤ max)
# Both values are inclusive.

min_rarity_weekly = 1.0
max_rarity_weekly = 197.0
